// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/6/2026, 8:27:11 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/macbookair/develop/laundry-platform/frontend/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/macbookair/develop/laundry-platform/frontend/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/macbookair/develop/laundry-platform/frontend/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/macbookair/develop/laundry-platform/frontend/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/macbookair/develop/laundry-platform/frontend/app/plugins/**/*.{js,ts,mjs}","/Users/macbookair/develop/laundry-platform/frontend/app/composables/**/*.{js,ts,mjs}","/Users/macbookair/develop/laundry-platform/frontend/app/utils/**/*.{js,ts,mjs}","/Users/macbookair/develop/laundry-platform/frontend/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/macbookair/develop/laundry-platform/frontend/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/macbookair/develop/laundry-platform/frontend/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;